export { default as HeroImg } from './Hero.jpg'
export { default as MenuImage } from './Menu-image.png'
export { default as Dishes } from './Dishes.jpg'
export { default as Image12 } from './12.jpg'
export { default as Image1 } from './1.jpg'
export { default as Image2 } from './2.jpg'
export { default as Image3 } from './3.jpg'