import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Auth0ProviderWithNavigate from "@/auth/Auth0ProviderWithNavigate";
import ReactQueryProvider from "@/api/reactQuerySetup";
import { Toaster } from "sonner";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <Auth0ProviderWithNavigate>
            <Header />
            {children}
            <Toaster visibleToasts={1} position="bottom-right" richColors  />
            <Footer />
          </Auth0ProviderWithNavigate>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
