import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Auth0ProviderWithNavigate from "@/auth/Auth0ProviderWithNavigate";
import ReactQueryProvider from "@/api/reactQuerySetup";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BiteZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
            <Auth0ProviderWithNavigate>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                <Header />
                {children}
                <Toaster visibleToasts={1} position="bottom-right" richColors />
                <Footer />
              </ThemeProvider>
            </Auth0ProviderWithNavigate>
          </ReactQueryProvider>
        </body>
      </html>
    </>
  );
}
